### ISSUE TITLE
Briem Curve Compensation Prep.py: Slant Offset Explanation

### ISSUE THREAD

**Issue by chrisjansky** [jpt/font-scripts#5]
Hi,

Love your scripts! Just wondering how the offset (line 34) is calculated—the commented out link to https://robofont.com/documentation/how-tos/working-with-italic-slant/#setting-the-italic-slant-offset returns 404.

Could you share any rationale on how/why the offset is added?

Thanks!

**Comment by jpt** [comment]
hi @chrisjansky - sorry about that, thanks for reporting! it looks like you can still access that document via archive.org: https://web.archive.org/web/20201021022942/https://robofont.com/documentation/how-tos/working-with-italic-slant/

the rationale is that if you slant a letter by (for example) 10º, it will no longer be centered in the bounding box of the glyph, so you'll need to apply a small negative offset to correct the sidebearings.  any time we apply a transformation to a path or layer  we have to tell Glyphs what the origin of the transformation is. by default this is 1/2 the x-height.

so if we know what the italic angle is (10º) and we know we're using half the x-height as the origin of our slant, we can apply the slant transformation, and then apply an offset to shift the glyph back after slanting so that the sidebearings are correct again:

`tan(angle * pi / 180) * (xHeight * 0.5)`

here we get into some trigonometry but it's not too bad:

the `(angle * pi / 180)` part just converts from degrees (e.g. 10) to radians — the tangent (`tan`)  uses radians, not degrees.  then we multiply by half the x-height so that we're actually measuring at the origin of the transformation

[this video is a good intro to trigonometry](https://channel9.msdn.com/Series/Sketchbooktutorial/Trigonometry-for-Designers-Dont-Panic) if you're curious about degrees vs. radians. and [here is some info about tangents](http://www2.clarku.edu/faculty/djoyce/trig/tangents.html).

I hope that answers the question! I wish I could explain `tan` better myself, but I'm just not that good at math :) glad you like the scripts!

**Comment by chrisjansky** [comment]
Thanks for the comprehensive reply, makes sense!

Sorry, my bad—looks like I’ve failed to understand what the offset represents. I’ve confused it for the slant degree compensation that happens in all verticals (and AFAIK more in uppercase), i.e. H is a bit less slanted than h.

I’ve come across such method that arguably results in a better italic, but I am curious to know more: why exactly is that so and how it is calculated—if that’s the intended behaviour of the script, could you elaborate please?

Attaching a result of the script on H after setting italic angle to 18deg—the verticals are 7.4 points away from vertical. 

Thanks!

<img width="706" alt="Screenshot 2021-10-16 at 10 25 05" src="https://user-images.githubusercontent.com/5342612/137580472-4cba33d2-8139-4a39-9653-92f179ddf9dd.png">

**Comment by jpt** [comment]
hi! this script is meant for slanting round letters, and none of the outputs are final results. it just preps some layers for you, so you can complete the process. this process used to be detailed here, but it looks like the website is down. http://66.147.242.192/~operinan/2/2.3.4a/2.3.4.34.curves.htm

I hope briem does not mind if I include an old screenshot here. 

![briem_curve_compensation](https://user-images.githubusercontent.com/5319916/137603902-a8a86d6e-c4be-4fa8-b3d5-1e5f67854cbd.png)

**Comment by chrisjansky** [comment]
Thanks for the screenshot @jpt.

So the not-so-exact slanting of verticals is not intentional and should be corrected afterwards? I am aware that it’s largely a subjective issue so I am just trying to gather some opinions—I’ve heard some folks slant uppercase a bit less for them to blend in with lowercase, so I wonder if this is the case 🙃

**Comment by jpt** [comment]
as I said this script is intended for round letters like "O" not "H" 
but I don't think I understand the problem you're having, unfortunately. can you explain what you mean by verticals, and slant compensation?

the script slants normally the same way it would if you went to the path menu and selected "Tranformations" and slanted it that way, then adjusts the sidebearings with the offset. can you confirm that the result is different? 

from the script:

```
for path in slantedLayer.paths:
        path.applyTransform([1,0,radians(angle),1,offset,0])
```

if `angle` is 18, and let's say `offset` is -40, the script would be doing the same thing as this from within the app (Path->Transformations)



<img width="236" alt="Screen Shot 2021-10-17 at 1 11 24 AM" src="https://user-images.githubusercontent.com/5319916/137618044-32017c50-ef72-44ae-891f-aca6356188de.png">
